name: CI

on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Use scpecific Node Version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Depencendies
        run: npm ci

      - name: Check Code Formating
        run: npm run format:check

      - name: Run Tests
        run: npm test -- --coverage
        env:
          CI: true
      

      

