name: Container
on: [push]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: node:17-alpine3.12
    
    steps:
      - name: test
        run: |
          node -v 
          cat /etc/os-release