name: Handling Workflow
on: 
  # - cron: "minuts hours dayOfMonth month dayOfWeek"
  schedule:
    - cron: "0/5 * * * *"
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "Testing if string is echoed"