name: Handling Workflow
on:
  # - cron: "minuts hours dayOfMonth month dayOfWeek"
  # schedule:
  #   - cron: "0/5 * * * *"
  # push:
  # pull_request:
  #   types: [closed, assigned, opened, reopened]
  repository_dispatch:
    types: [ build ]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checks Payload from post 
        run: echo ${{ github.event.client_payload.env }}