name: Handling Workflow
on: 
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Testing if string is echoed"